server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  application:
    name: msa-weather-report-eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

