server:
#  port: 8089
  servlet:
    context-path: /

spring:
  application:
    name: micro-weather-config-client
  cloud:
    config:
      profile: dev
#      uri: http://localhost:8888
      discovery:
        enabled: true
        service-id: micro-weather-config-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

