server:
  port: 8083
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: msa-weather-collection-eureka-feign

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000