server:
  port: 8088
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  application:
    name: msa-weather-report-eureka-feign-geteway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000