server:
  port: 8888
  servlet:
    context-path: /

spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jdiop417/Learning
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

